src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContactRepository::class)]
class Contact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 25)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 25)]
    private ?string $Nom = null;

    #[ORM\Column(length: 50)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $Sujet = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Message = null;

    #[ORM\Column(options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $Date_creation = null;

    public function __construct()
    {
        $this->Date_creation = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): static
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getSujet(): ?string
    {
        return $this->Sujet;
    }

    public function setSujet(string $Sujet): static
    {
        $this->Sujet = $Sujet;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(string $Message): static
    {
        $this->Message = $Message;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeImmutable
    {
        return $this->Date_creation;
    }

    public function setDateCreation(\DateTimeImmutable $Date_creation): static
    {
        $this->Date_creation = $Date_creation;

        return $this;
    }
}

templates/components/modal.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="relative">
        <button id="dropdownButton" class="flex items-center border border-custom_boutton bg-custom_green_dark rounded-full overflow-hidden" onclick="document.getElementById('lines').classList.toggle('active')">
            <div id="lines" class="flex flex-col justify-around h-full px-4">
                <div class="w-6 h-0.5 bg-white mb-1 transform transition-transform duration-200 origin-center"></div>
                <div class="w-6 h-0.5 bg-white mb-1 opacity-100 transition-opacity duration-200"></div>
                <div class="w-6 h-0.5 bg-white transform transition-transform duration-200 origin-center"></div>
            </div>
            <div class="bg-custom_boutton text-custom_green_dark font-bold text-2xl py-2 px-4 rounded-full md:w-8 md:h-8 lg:w-10 lg:h-10 flex items-center justify-center text-md">
                {{ app.user.prenom|slice(0, 1)|upper }}
            </div>
        </button>  
        <div id="dropdownMenu" class="hidden absolute border border-custom_green_dark right-0 mt-2 w-48 bg-custom-green rounded-lg shadow-lg z-50">
            <a href="/reserver" class="block px-4 py-2 text-sm text-gray-700 font-semibold hover:bg-custom_green_dark hover:text-white rounded-t-md">Réservations</a>
            <a href="/mes-favoris" class="block px-4 py-2 text-sm text-gray-700 font-semibold hover:bg-custom_green_dark hover:text-white">Favoris</a>
            <div class="mx-4 border-t border-gray-300"></div>
            <a href="/mes-locations" class="block px-4 py-2 text-sm text-gray-700 hover:bg-custom_green_dark hover:text-white">Mes Biens</a>
            <a href="/profil" class="block px-4 py-2 text-sm text-gray-700 hover:bg-custom_green_dark hover:text-white">Mon Compte</a>
            <a href="/user/invoices" class="block px-4 py-2 text-sm text-gray-700 hover:bg-custom_green_dark hover:text-white">Mes Factures</a>
            {% if is_granted('ROLE_ADMIN') %}
                <a href="/admin" class="block px-4 py-2 text-sm text-gray-700 hover:bg-custom_green_dark hover:text-white">Administration</a>
            {% endif %}
            <div class="mx-4 border-t border-gray-300"></div>
            <a href="/logout" class="block px-4 py-2 text-sm text-gray-700 hover:bg-custom_green_dark hover:text-white rounded-b-md">Déconnexion</a>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    <style>
        #lines.active div:nth-child(1) {
            transform: rotate(-45deg) translate(-2px, 6px);
        }
        #lines.active div:nth-child(2) {
            opacity: 0;
        }
        #lines.active div:nth-child(3) {
            transform: rotate(45deg) translate(-2px, -6px);
        }
    </style>
{% endblock %}

templates/components/modalFormulaire.html.twig
<h2 class="font-cotorisHeavy text-6xl p-4">Bonjour</h2>
<p class="text-xl mb-4 ml-4">
    {% if app.user %}
    {{ app.user.Prenom }} {{ app.user.Nom }}
    {% endif %}
</p>
<ul>
    {% if app.user %}
    <li
        class="w-full hover:bg-custom_green_dark block text-lg font-semibold py-2 hover:text-white {{ app.request.attributes.get('_route') == 'app_profil' ? 'bg-custom_green_dark text-white' : '' }}">
        <a href="{{ path('app_profil') }}" class="block ml-4">
           Mes informations personnelles
        </a>
    </li>
    <div class="border-t border-custom_green_dark"></div>
    <li
        class="w-full hover:bg-custom_green_dark block text-lg font-semibold py-2 hover:text-white {{ app.request.attributes.get('_route') == 'app_reserver' ? 'bg-custom_green_dark text-white' : '' }}">
        <a href="{{ path('app_reserver') }}" class="block ml-4">
            Mes réservations
        </a>
    </li>
    <div class="border-t border-custom_green_dark"></div>
    <li
        class="w-full hover:bg-custom_green_dark block text-lg font-semibold py-2 hover:text-white {{ app.request.attributes.get('_route') == 'app_add_location' ? 'bg-custom_green_dark text-white' : '' }}">
        <a href="{{ path('app_add_location') }}" class="block ml-4">
            Mettre en location
        </a>
    </li>
    <div class="border-t border-custom_green_dark"></div>
    {% else %}
    <li
        class="w-full hover:bg-custom_green_dark block text-lg font-semibold py-2 hover:text-white {{ app.request.attributes.get('_route') == 'app_add_location' ? 'bg-custom_green_dark text-white' : '' }}">
        <a href="{{ path('app_login') }}" class="block ml-4">Connectez-vous !</a>
    </li>
    <div class="border-t border-custom_green_dark"></div>
    {% endif %}
    <li
        class="w-full hover:bg-custom_green_dark block text-lg font-semibold py-2 hover:text-white {{ app.request.attributes.get('_route') == 'app_mes_favoris' ? 'bg-custom_green_dark text-white' : '' }}">
        <a href="{{ path('app_mes_favoris') }}" class="block ml-4">
            Favoris
        </a>
    </li>
    <div class="border-t border-custom_green_dark"></div>
    <li
        class="w-full hover:bg-custom_green_dark block text-lg font-semibold py-2 hover:text-white rounded-b-md {{ app.request.attributes.get('_route') == 'app_contact' ? 'bg-custom_green_dark text-white' : '' }}">
        <a href="{{ path('app_contact') }}" class="block ml-4">
            Contact
        </a>
    </li>
</ul>

templates/components/modalMobile.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div id="navbar"
    class="md:hidden fixed bottom-0 left-0 w-full bg-custom_green_dark py-2 flex justify-center items-center z-[9999] space-x-6 transition-all duration-500">
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
    <a href="/mes-locations" class="text-custom-green font-bold flex flex-col items-center py-2">
        <i class="fas fa-home fa-lg mb-1"></i>
    </a>
    <a href="/reserver" class="text-custom-green font-bold flex flex-col items-center py-2">
        <i class="fas fa-calendar-alt fa-lg mb-1"></i>
    </a>
    <a href="/mes-favoris" class="text-custom-green font-bold flex flex-col items-center py-2">
        <i class="fas fa-heart fa-lg mb-1"></i>
    </a>
    <a href="/profil" class="text-custom-green font-bold flex flex-col items-center py-2">
        <i class="fas fa-user-circle fa-lg mb-1"></i>
    </a>
    <a href="/user/invoices" class="text-custom-green font-bold flex flex-col items-center py-2">
        <i class="fas fa-file-invoice fa-lg mb-1"></i>
    </a>
    {% else %}
    <a href="/login" class="text-custom-green font-bold flex flex-col items-center py-2">
        <i class="fas fa-user-circle fa-lg mb-1"></i>
    </a>
    {% endif %}
    <a href="/contact" class="text-custom-green font-bold flex flex-col items-center py-2">
        <i class="fas fa-envelope fa-lg mb-1"></i>
    </a>
</div>

<script>
    let lastScrollTop = 0;
    const navbar = document.getElementById('navbar');
    const bottomMargin = 100;

    window.addEventListener('scroll', function () {
        let scrollTop = window.pageYOffset || document.documentElement.scrollTop;
        let scrollHeight = document.documentElement.scrollHeight - document.documentElement.clientHeight;
        if ((scrollTop > lastScrollTop && scrollTop > 0) || (scrollTop + bottomMargin >= scrollHeight)) {
            navbar.style.bottom = '-60px';
        } else {
            navbar.style.bottom = '0';
        }
        lastScrollTop = scrollTop;
    });
</script>

{% endblock %}