src/Entity/Locations.php
<?php

namespace App\Entity;

use App\Repository\LocationsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LocationsRepository::class)]
class Locations
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $Nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?float $Prix = null;

    #[ORM\Column(length: 255)]
    private ?string $Adresse = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Date_Debut_Disponibilite = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Date_Fin_Disponibilite = null;

    #[ORM\Column]
    private ?int $Capacite_maximal = null;

    #[ORM\Column]
    private ?bool $PMR = null;

    #[ORM\Column]
    private ?bool $Actif = null;

    #[ORM\ManyToOne(inversedBy: 'locations')]
    private ?Utilisateurs $Utilisateurs = null;

    #[ORM\ManyToMany(targetEntity: Categories::class, inversedBy: 'locations')]
    private Collection $Categories;

    #[ORM\OneToMany(mappedBy: 'Locations', targetEntity: Images::class, orphanRemoval: true, cascade: ['persist'])]
    private Collection $images;

    #[ORM\ManyToMany(targetEntity: Equipements::class, mappedBy: 'Locations', cascade: ['persist', 'remove'])]
    private Collection $Equipements;

    public function __construct()
    {
        $this->Categories = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->Equipements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(float $Prix): static
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): static
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getDateDebutDisponibilite(): ?\DateTimeInterface
    {
        return $this->Date_Debut_Disponibilite;
    }

    public function setDateDebutDisponibilite(\DateTimeInterface $Date_Debut_Disponibilite): static
    {
        $this->Date_Debut_Disponibilite = $Date_Debut_Disponibilite;

        return $this;
    }

    public function getDateFinDisponibilite(): ?\DateTimeInterface
    {
        return $this->Date_Fin_Disponibilite;
    }

    public function setDateFinDisponibilite(\DateTimeInterface $Date_Fin_Disponibilite): static
    {
        $this->Date_Fin_Disponibilite = $Date_Fin_Disponibilite;

        return $this;
    }

    public function getCapaciteMaximal(): ?int
    {
        return $this->Capacite_maximal;
    }

    public function setCapaciteMaximal(int $Capacite_maximal): static
    {
        $this->Capacite_maximal = $Capacite_maximal;

        return $this;
    }

    public function isPMR(): ?bool
    {
        return $this->PMR;
    }

    public function setPMR(bool $PMR): static
    {
        $this->PMR = $PMR;

        return $this;
    }

    public function isActif(): ?bool
    {
        return $this->Actif;
    }

    public function setActif(bool $Actif): static
    {
        $this->Actif = $Actif;

        return $this;
    }

    public function getUtilisateurs(): ?Utilisateurs
    {
        return $this->Utilisateurs;
    }

    public function setUtilisateurs(?Utilisateurs $Utilisateurs): static
    {
        $this->Utilisateurs = $Utilisateurs;

        return $this;
    }

    /**
     * @return Collection<int, Categories>
     */
    public function getCategories(): Collection
    {
        return $this->Categories;
    }

    public function addCategory(Categories $category): static
    {
        if (!$this->Categories->contains($category)) {
            $this->Categories->add($category);
        }

        return $this;
    }

    public function removeCategory(Categories $category): static
    {
        $this->Categories->removeElement($category);

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setLocations($this);
        }

        return $this;
    }

    public function removeImage(Images $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getLocations() === $this) {
                $image->setLocations(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Equipements>
     */
    public function getEquipements(): Collection
    {
        return $this->Equipements;
    }

    public function addEquipement(Equipements $equipement): static
    {
        if (!$this->Equipements->contains($equipement)) {
            $this->Equipements->add($equipement);
            $equipement->addLocation($this);
        }

        return $this;
    }

    public function removeEquipement(Equipements $equipement): static
    {
        if ($this->Equipements->removeElement($equipement)) {
            $equipement->removeLocation($this);
        }

        return $this;
    }
}

src/Controller/LocationsController.php
<?php

namespace App\Controller;

use App\Entity\Commenter;
use App\Repository\CategoriesRepository;
use App\Repository\LocationsRepository;
use App\Repository\AjouterEnFavorisRepository;
use App\Repository\ReserverRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Reserver;
use App\Form\ReserverType;
use App\Repository\CommenterRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;

class LocationsController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function Home(
        Request $request,
        CategoriesRepository $categoriesRepo,
        LocationsRepository $locationsRepo,
        AjouterEnFavorisRepository $favorisRepo
    ): Response {
        $categories = $categoriesRepo->findAll();
        $locations = $locationsRepo->findAll();

        // Obtenir l'utilisateur actuel
        $user = $this->getUser();

        $favoris = [];
        if ($user) {
            // Obtenir les favoris de l'utilisateur actuel
            $favoris = $favorisRepo->findFavoritesByUser($user->getId());
        }

        // Récupérer les valeurs de recherche à partir de la requête
        $location = $request->query->get('location');
        $startDate = $request->query->get('start_date');
        $endDate = $request->query->get('end_date');
        $partySize = $request->query->get('party_size');

        // Utiliser les valeurs de recherche pour filtrer les locations
        $locations = $locationsRepo->search($location, $startDate, $endDate, $partySize);

        return $this->render('home/index.html.twig', [
            "categories" => $categories,
            "locations" => $locations,
            "favoris" => $favoris
        ]);
    }

    #[Route('/location/{id}', name: 'app_location')]
    public function Location($id, LocationsRepository $locationsRepo, ReserverRepository $reserverRepo, CommenterRepository $commenterRepo, AjouterEnFavorisRepository $favorisRepo, Request $request, EntityManagerInterface $em): Response
    {
        $location = $locationsRepo->find($id);

        // Récupération des réservations associées à la location
        $reservations = $reserverRepo->findBy(['Locations' => $location]);

        // Récupération des commentaires associés à la location
        $comments = $commenterRepo->findByLocation($id);

        // Obtenir l'utilisateur actuel
        $user = $this->getUser();

        $favoris = [];
        if ($user) {
            // Obtenir les favoris de l'utilisateur actuel
            $favoris = $favorisRepo->findFavoritesByUser($user->getId());
        }

        // Création d'une nouvelle réservation
        $reservation = new Reserver();

        $reservation->setStatut('transmis');

        // Création du formulaire
        $reservationForm = $this->createForm(ReserverType::class, $reservation, [
            'max_capacity' => $location->getCapaciteMaximal(),
        ]);
        // Traitement de la requête du formulaire
        $reservationForm->handleRequest($request);

        // Vérification de la soumission et de la validité du formulaire
        if ($reservationForm->isSubmitted() && $reservationForm->isValid()) {
            // Vérifiez si les dates de réservation sont disponibles
            $dateDebut = $reservation->getDateDebut();
            $dateFin = $reservation->getDateFin();

            $nombreDeLocataires = $reservation->getNombresDeLocataires();
            $capaciteMaximale = $location->getCapaciteMaximal();

            // Calcule le nombre de jours
            $nombreDeJours = $dateDebut->diff($dateFin)->days;

            // Ajoute 1 au nombre de jours
            $nombreDeJours += 1;

            // Calcule le prix total
            $prixTotal = $nombreDeJours * $location->getPrix();

            $session = $request->getSession();

            // Stocke le prix total dans la session
            $session->set('prixTotal', $prixTotal);

            // Stocke le nombre de jours dans la session
            $session->set('nombreDeJours', $nombreDeJours);

            if ($location->getDateDebutDisponibilite() <= $dateDebut && $location->getDateFinDisponibilite() >= $dateFin) {
                // Vérifiez si le nombre de locataires est inférieur ou égal à la capacité maximale
                if ($nombreDeLocataires <= $capaciteMaximale) {
                    $session = $request->getSession();
                    $session->set('reservation', $reservation);

                    return $this->redirectToRoute('app_paiement', ['id' => $location->getId()]);
                } else {
                    $this->addFlash('error', 'Le nombre de locataires est supérieur à la capacité maximale.');
                }
            } else {
                $this->addFlash('error', 'Les dates sélectionnées ne sont pas disponibles.');
            }
        }

        // Récupère les commentaires de la base de données
        $commentaires = $em->getRepository(Commenter::class)->findBy(['Locations' => $location]);

        // Calcule la note moyenne
        $noteMoyenne = 0;
        if (count($commentaires) > 0) {
            $noteMoyenne = array_sum(array_map(function ($commentaire) {
                return $commentaire->getNoteLoueur();
            }, $commentaires)) / count($commentaires);
        }

        // Formatte la note moyenne avec un chiffre après la virgule
        $noteMoyenne = number_format($noteMoyenne, 1);

        // Calcule le nombre total de notes
        $totalNotes = count($commentaires);

        // Calcule le nombre de commentaires pour chaque note
        $statistiquesNotes = [];
        for ($i = 0; $i <= 5; $i++) {
            $statistiquesNotes[$i] = count($em->getRepository(Commenter::class)->findBy(['Note_Loueur' => $i, 'Locations' => $location]));
        }

        // Trie les notes en ordre décroissant
        krsort($statistiquesNotes);

        return $this->render('home/location.html.twig', [
            "location" => $location,
            'reservationForm' => $reservationForm->createView(),
            'comments' => $comments,
            "favoris" => $favoris,
            'commentaires' => $commentaires,
            'reservations' => $reservations,
            'noteMoyenne' => $noteMoyenne,
            'totalNotes' => $totalNotes,
            'statistiquesNotes' => $statistiquesNotes,

        ]);
    }
}

templates/locations/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Locations{% endblock %}

{% block body %}
<div class="mx-auto md:py-4 md:px-20 bg-custom-green">
    {% include 'header.html.twig' %}
    <div class="flex justify-between items-center md:hidden py-2 ml-2">
        <a href="{{ path('app_home') }}" class="md:hidden flex items-center py-2">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke="currentColor"
                class="h-6 w-6">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
            </svg>
            Locations
        </a>
    </div>
    {% for message in app.flashes('success') %}
    <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative animate-slide-down text-center" role="alert" style="animation: slideDown 5s ease-in-out forwards; position: fixed; top: 2%; left: 0; right: 0; width: max-content; margin-left: auto; margin-right: auto;">
        <strong class="font-bold">Succès !</strong>
        <span class="block sm:inline">{{ message }}</span>
    </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative animate-slide-down text-center" role="alert" style="animation: slideDown 5s ease-in-out forwards; position: fixed; top: 2%; left: 0; right: 0; width: max-content; margin-left: auto; margin-right: auto;">
        <strong class="font-bold">Erreur !</strong>
        <span class="block sm:inline">{{ message }}</span>
    </div>
    {% endfor %}
    <div class="flex justify-center md:mt-6">
        <h1 class="font-cotorisHeavy text-3xl lg:mt-6 mb-6">Vos biens</h1>
    </div>
    {% if locations is empty %}
    <div class="flex justify-center mt-4">
        <p>Vous n'avez aucune location.</p>
    </div>
    {% else %}
    <div class="hidden lg:flex lg:justify-center">
        <!-- Tableau pour les écrans moyens et plus grands -->
        <table class="table-auto">
            <thead>
                <tr>
                    <th class="px-4 py-2">Image</th>
                    <th class="px-4 py-2">Nom</th>
                    <th class="px-4 py-2">Adresse</th>
                    <th class="px-4 py-2">Prix</th>
                    <th class="px-4 py-2">Catégorie</th>
                    <th class="px-4 py-2">Consulter les Réservations</th>
                    <th class="px-4 py-2">Modifier</th>
                    <th class="px-4 py-2">Supprimer</th>
                </tr>
            </thead>
            <tbody>
                {% for location in locations %}
                <tr>
                    <td class="border px-4 py-4">
                        <div class="flex justify-center items-center">
                            {% if location.getImages()|length > 0 %}
                            <img src="{{ asset('uploads/' ~ location.getImages()[0].getNom()) }}"
                                alt="{{ location.getImages()[0].getNom() }}" class="w-24 h-24 object-cover">
                            {% endif %}
                        </div>
                    </td>
                    <td class="border px-4 py-4">
                        <div class="flex justify-center items-center">{{ location.nom|length > 20 ? location.nom|slice(0, 20) ~ '...' : location.nom }}</div>
                    </td>
                    <td class="border px-4 py-4">
                        <div class="flex justify-center items-center">{{ location.Adresse|length > 20 ? location.Adresse|slice(0, 2) ~ '...' : location.Adresse }}</div>
                    </td>
                    <td class="border px-4 py-4">
                        <div class="flex justify-center items-center">{{ location.getPrix() }}€</div>
                    </td>
                    <td class="border px-4 py-4">
                        <div class="flex justify-center items-center">
                            {% for categorie in location.getCategories() %}
                            {{ categorie.getLibelle() }}
                            {% endfor %}
                        </div>
                    </td>
                    <td class="border px-4 py-4">
                        <div class="flex justify-center items-center">
                            <a href="{{ path('location_reservations', {'id': location.getId()}) }}"
                                class="px-4 py-2 bg-custom_green_dark text-white rounded">Consulter</a>
                        </div>
                    </td>
                    <td class="border px-4 py-4">
                        <div class="flex justify-center items-center">
                            <a href="{{ path('app_edit_location', {'id': location.getId()}) }}"
                                class="px-4 py-2 bg-custom_green_dark text-white rounded">Modifier</a>
                        </div>
                    </td>
                    <td class="border px-4 py-4">
                        <div class="flex justify-center items-center">
                            <form id="delete-form-{{ location.getId() }}"
                                action="{{ path('app_delete_location', {'id': location.getId()}) }}" method="post"
                                class="hidden">
                                <input type="hidden" name="_method" value="DELETE">
                            </form>
                            <a href="#" class="px-4 py-2 bg-custom_green_dark text-white rounded delete-button"
                                data-delete-form="delete-form-{{ location.getId() }}">Supprimer</a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div id="delete-confirm-popin"
        class="fixed top-0 left-0 w-full h-full flex items-center justify-center bg-black bg-opacity-50 hidden">
        <div class="bg-white p-4 rounded">
            <p>Êtes-vous sûr de vouloir supprimer ce bien ?</p>
            <div class="flex justify-end mt-2">
                <button id="delete-confirm-yes"
                    class="px-4 py-2 bg-custom_green_dark text-white rounded mr-2">Oui</button>
                <button id="delete-confirm-no" class="px-4 py-2 bg-custom_green_dark text-white rounded">Non</button>
            </div>
        </div>
    </div>

    <div class="lg:hidden flex flex-col ml-4 mr-4">
        <!-- Cartes pour les écrans plus petits -->
        {% for location in locations %}
        <div class="bg-white my-2 shadow-lg rounded-lg p-4">
            <div class="flex flex-col items-center">
                <h2 class="font-bold">{{ location.getNom() }}</h2>
                <p>{{ location.getAdresse() }}</p>
                <p>{{ location.getPrix() }} €</p>
                {% for categorie in location.getCategories() %}
                <p>{{ categorie.getLibelle() }}</p>
                {% endfor %}
                {% if location.getImages()|length > 0 %}
                <img src="{{ asset('uploads/' ~ location.getImages()[0].getNom()) }}"
                    alt="{{ location.getImages()[0].getNom() }}" class="w-24 h-24 object-cover">
                {% endif %}
                <a href="{{ path('location_reservations', {'id': location.getId()}) }}"
                    class="px-4 py-2 mt-2 bg-custom_green_dark text-white rounded">Consulter</a>
            </div>
            <div class="flex justify-between mt-2">
                <a href="{{ path('app_edit_location', {'id': location.getId()}) }}"
                    class="px-4 py-2 bg-custom_green_dark text-white rounded">Modifier</a>
                <form id="delete-form-{{ location.getId() }}"
                    action="{{ path('app_delete_location', {'id': location.getId()}) }}" method="post"
                    class="hidden">
                    <input type="hidden" name="_method" value="DELETE">
                </form>
                <a href="#" class="px-4 py-2 bg-custom_green_dark text-white rounded delete-button"
                    data-delete-form="delete-form-{{ location.getId() }}">Supprimer</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    {% if totalPages > 1 %}
    <div class="flex justify-center mt-4">
        <a href="{{ currentPage > 1 ? path('mes_locations', {'page': currentPage - 1}) : '#' }}"
            class="px-3 py-2 border border-gray-300 text-custom_green_dark rounded-l">{{ '<<' }}</a>
                {% for page in 1..totalPages %}
                <a href="{{ path('mes_locations', {'page': page}) }}"
                    class="{{ page == currentPage ? 'bg-custom_green_dark text-white' : 'text-custom_green_dark' }} px-3 py-2 border border-gray-300">{{
                    page }}</a>
                {% endfor %}
                <a href="{{ currentPage < totalPages ? path('mes_locations', {'page': currentPage + 1}) : '#' }}"
                    class="px-3 py-2 border border-gray-300 text-custom_green_dark rounded-r">{{ '>>' }}</a>
    </div>
    {% endif %}

    <div class="flex justify-center mt-4">
        <a href="{{ path('app_add_location') }}"
            class="w-60 py-2 mb-4 bg-custom_green_dark text-custom-green font-cotorisHeavy rounded-full text-center">Ajouter
            une nouvelle location</a>
    </div>
</div>

{% include 'components/modalMobile.html.twig' %}

{% endblock %}

templates/locations/reservations.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservations{% endblock %}

{% block body %}
<div class="mx-auto md:py-4 md:px-20 bg-custom-green">
    {% include 'header.html.twig' %}
    <div class="flex justify-between items-center md:hidden py-2 ml-2">
        <a href="{{ path('mes_locations') }}" class="md:hidden flex items-center py-2">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke="currentColor"
                class="h-6 w-6">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
            </svg>
            Mes biens
        </a>
    </div>
    <div class="flex justify-center md:mt-6">
        <h1 class="font-cotorisHeavy text-3xl lg:mt-6 mb-6">Réservations</h1>
    </div>
    {% if reservations is empty %}
    <div class="flex justify-center mt-4">
        <p>Vous n'avez aucune réservation.</p>
    </div>
    {% else %}
    <div class="hidden sm:flex sm:justify-center">
        <!-- Tableau pour les écrans moyens et plus grands -->
        <table class="table-auto">
            <thead>
                <tr>
                    <th class="px-4 py-2">Date de début</th>
                    <th class="px-4 py-2">Date de fin</th>
                    <th class="px-4 py-2">Nom</th>
                    <th class="px-4 py-2">Prénom</th>
                    <th class="px-4 py-2">Contacter</th>
                </tr>
            </thead>
            <tbody>
                {% for reservation in reservations %}
                <tr>
                    <td class="border px-4 py-4">
                        <div class="flex justify-center items-center">{{ reservation.DateDebut|date('d-m-Y') }}</div>
                    </td>
                    <td class="border px-4 py-4">
                        <div class="flex justify-center items-center">{{ reservation.DateFin|date('d-m-Y') }}</div>
                    </td>
                    <td class="border px-4 py-4">
                        <div class="flex justify-center items-center">{{ reservation.Utilisateurs.Nom }}</div>
                    </td>
                    <td class="border px-4 py-4">
                        <div class="flex justify-center items-center">{{ reservation.Utilisateurs.Prenom }}</div>
                    </td>
                    <td class="border px-4 py-4">
                        <div class="flex justify-center items-center">
                            <a href="tel:{{ reservation.Utilisateurs.Telephone }}"
                                class="px-4 py-2 bg-custom_green_dark text-white rounded">Appeler</a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="sm:hidden flex flex-col ml-4 mr-4">
        <!-- Cartes pour les écrans plus petits -->
        {% for reservation in reservations %}
        <div class="bg-white my-2 shadow-lg rounded-lg p-4">
            <div class="flex flex-col items-center">
                <h2 class="font-bold">{{ reservation.Utilisateurs.Prenom }} {{ reservation.Utilisateurs.Nom }}</h2>
                <p>{{ reservation.DateDebut|date('d-m-Y') }}</p>
                <p>{{ reservation.DateFin|date('d-m-Y') }}</p>
                <a href="tel:{{ reservation.Utilisateurs.Telephone }}"
                    class="px-4 py-2 bg-custom_green_dark text-white rounded">Appeler</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    {% if reservations|length > reservationsPerPage and totalPages > 1 %}
    <div class="flex justify-center mt-4">
        <a href="{{ currentPage > 1 ? path('location_reservations', {'id': location.id, 'page': currentPage - 1}) : '#' }}"
            class="px-3 py-2 border border-gray-300 text-custom_green_dark rounded-l">{{ '<<' }}</a>
        {% for page in 1..totalPages %}
        <a href="{{ path('location_reservations', {'id': location.id, 'page': page}) }}"
            class="{{ page == currentPage ? 'bg-custom_green_dark text-white' : 'text-custom_green_dark' }} px-3 py-2 border border-gray-300">{{ page }}</a>
        {% endfor %}
        <a href="{{ currentPage < totalPages ? path('location_reservations', {'id': location.id, 'page': currentPage + 1}) : '#' }}"
            class="px-3 py-2 border border-gray-300 text-custom_green_dark rounded-r">{{ '>>' }}</a>
    </div>
    {% endif %}
</div>

{% include 'components/modalMobile.html.twig' %}

{% endblock %}